PieceMeal/FoodCap

package-lock.json, package.json, script/seed.js, server/db/models/user.js, server/db/neo.js
fixes #3 
Creating user will update postreSQL and Neo4j with new user information.
Every time user is created new UUID is assigned to that user.
UUID's are passed to NEO4J as unique ID's we'll be using to find the node's
=> neo4j-sync-sequelize

script/dbCleanup.js
dbCleanup.js is a parser function to go through the db.json file we got from the scraper and pull out the info we need to create a node in Neo4j.  Nothing is happening with the data right now, but the 6 pieces of info listed will go on the nodes.
=> added a db parser function to pull out pertinent info from json

server/api/index.js, server/api/lists.js, server/api/lists.spec.js, server/utils/apiMiddleware.js, server/utils/createUsers.js
I added some middleware functions I used for my API for grace shopper. I can explain them in a meeting.
I started working on lists. I commented out my API route and added unit tests for them
Currently existing routes:
POST(/api/list) -- creates a list with given name. adds HAS_LIST edge between user and list
GET(/api/list) -- gets all lists from logged in user with HAS_LIST edge
PUT(/api/lists/favorite) -- creates a IS_FAVORITE relationship between logged in user and a list given list  UUID
I think we might need to use UUIDs for things that need to be searched for that don't have a unique name
=> added middleware functions. added 3 list routes with unit tests

.travis.yml, client/components/MyList.js, script/database.json, script/seed.js, server/api/lists.js
GET /api/lists/:listID now includes info from the isIngredient relationship
Made sure front end uses that info
=> added ingredients to api route and connected to component

script/seed.js, server/db/models/user.js, server/db/neo.js
added a helper function that fixed seed
=> fixed seed

script/seed.js, server/api/lists.js
=> reshaping data from api

server/api/lists.js
=> rewrote api request

client/components/SingleRecipe.js, public/index.html, script/seed.js, server/api/recipes.js
- added recommendation search by user in api/recipes
- added some css to singlerecipe
- add some random views to seed file
=> Recommends

.travis.yml, client/components/user-home.spec.js, client/store/user.spec.js, script/seed.js, script/seed.spec.js, server/api/lists.spec.js, server/api/users.spec.js, server/db/models/user.spec.js, server/db/neo.js
=> Travistest

client/components/MyList.js, client/store/list.js, server/api/lists.js
added forms (need to be formatted) for adding an item to list
=> can add items to list

client/components/Preferences.js, client/routes.js
=> fixed routes to display navbar

client/components/SingleRecipe.js, client/components/userHome.js, client/routes.js, client/store/user.js, server/api/users.js
fixes #52 #33 
Rec engine changed
=> preferences and category rec engine on singup

client/components/MyList.js, client/store/list.js, package-lock.json, package.json, server/api/lists.js, server/utils/createUsers.js
added api route to just update note on ingredient on list
added corresponding parts to redux store
can now edit notes on MyList component
=> can now edit notes

client/store/user.spec.js, server/api/lists.js, server/api/lists.spec.js, server/api/users.spec.js, server/db/db.js, server/db/models/user.spec.js, server/utils/createUsers.js
=> fixed unit testing not freezing

client/components/navbar.js, client/components/userHome.js
buttons aren't hooked up...but here it is!
=> changed style of navbar

client/components/Review Components/ItemReviews.js, client/components/Review Components/ReviewForm.js, client/components/Review Components/ReviewList.js, client/components/Review Components/ReviewListItem.js, client/components/navbar.js, client/components/userHome.js
added a subfolder within components folder with all of my review stuff from grace shopper (nothing is hooked up to our site)
=> Review Components

client/components/IngredientRow.js, client/components/Ingredients.js, client/components/MyList.js, client/components/ShoppingList.js, client/components/index.js, client/routes.js, server/api/ingredients.js, server/api/lists.js
first version of shopping list
=> shopping list demo 1

script/categories.json, script/database.json
=> added cuisines

client/components/MyList.js
=> formatting

client/components/AllRecipes.js, client/components/RecipeList.js, client/components/SearchResults.js, client/routes.js, script/database.json, server/api/recipes.js, server/api/users.js
=> all view and search view cards fixed

server/api/users.js
=> fixed changing the preferences
